linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocyclo
    - dupl
    - misspell
    - unconvert
    - prealloc
    - gosec
  disable:
    - fieldalignment  # 禁用字段对齐检查，过于严格

linters-settings:
  gocyclo:
    min-complexity: 20  # 提高复杂度阈值
  dupl:
    threshold: 100
  govet:
    enable:
      - nilfunc
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: false
    check-blank: false

run:
  timeout: 5m
  go: "1.24"
